version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: mooorshum/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: mooorshum/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /staticfiles/
    volumes:
      - static:/staticfiles

  gateway:
    image: mooorshum/foodgram_gateway:latest
    env_file: .env
    ports:
      - 7000:91
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend
      - frontend
